-- ===========================================================================
-- P2-b（实际应用修正版 · 2026-09-06）
-- 由 information_schema 内省生成：全部 DROP/ADD FOREIGN KEY 使用真实约束名，
-- 顺序严格 DROP FK -> MODIFY 列 -> ADD FK。仅把 BIGINT 列（PK 与外键列）+UNSIGNED，
-- 保留 AUTO_INCREMENT（应用当前仍走自增，不破坏写入）。原手写版有 FK 命名错配已废弃。
-- ===========================================================================
-- P2-b 生成（内省真实库，FK 名真实，DROP FK -> MODIFY -> ADD FK 顺序）
-- 仅把 BIGINT 列（PK 与外键列）加 UNSIGNED；保留 AUTO_INCREMENT，应用当前仍走自增，不破坏写入。
ALTER TABLE `access_requests` DROP FOREIGN KEY `access_requests_reviewedBy_fkey`;
ALTER TABLE `allocation_lines` DROP FOREIGN KEY `allocation_lines_created_by_fkey`;
ALTER TABLE `allocation_lines` DROP FOREIGN KEY `allocation_lines_line_id_fkey`;
ALTER TABLE `allocation_lines` DROP FOREIGN KEY `allocation_lines_source_id_fkey`;
ALTER TABLE `archived_costs` DROP FOREIGN KEY `archived_costs_original_document_id_fkey`;
ALTER TABLE `archived_logistics` DROP FOREIGN KEY `archived_logistics_original_document_id_fkey`;
ALTER TABLE `archived_order_lines` DROP FOREIGN KEY `archived_order_lines_archived_order_id_fkey`;
ALTER TABLE `archived_orders` DROP FOREIGN KEY `archived_orders_original_document_id_fkey`;
ALTER TABLE `audit_logs` DROP FOREIGN KEY `audit_logs_customer_id_fkey`;
ALTER TABLE `audit_logs` DROP FOREIGN KEY `audit_logs_user_id_fkey`;
ALTER TABLE `authorization_codes` DROP FOREIGN KEY `authorization_codes_createdBy_fkey`;
ALTER TABLE `brand_unit_conversion` DROP FOREIGN KEY `brand_unit_conversion_specId_fkey`;
ALTER TABLE `brand_unit_conversion` DROP FOREIGN KEY `brand_unit_conversion_unitId_fkey`;
ALTER TABLE `cost_lines` DROP FOREIGN KEY `cost_lines_line_id_fkey`;
ALTER TABLE `cost_lines` DROP FOREIGN KEY `cost_lines_source_id_fkey`;
ALTER TABLE `cost_lines` DROP FOREIGN KEY `cost_lines_verified_by_fkey`;
ALTER TABLE `customer_addresses` DROP FOREIGN KEY `customer_addresses_customerId_fkey`;
ALTER TABLE `customer_contact` DROP FOREIGN KEY `customer_contact_customerId_fkey`;
ALTER TABLE `customer_invoice` DROP FOREIGN KEY `customer_invoice_customerId_fkey`;
ALTER TABLE `customer_sessions` DROP FOREIGN KEY `customer_sessions_authorizationCodeId_fkey`;
ALTER TABLE `customer_sessions` DROP FOREIGN KEY `customer_sessions_customerId_fkey`;
ALTER TABLE `delivery_records` DROP FOREIGN KEY `delivery_records_document_id_fkey`;
ALTER TABLE `document_lines` DROP FOREIGN KEY `document_lines_brandId_fkey`;
ALTER TABLE `document_lines` DROP FOREIGN KEY `document_lines_documentId_fkey`;
ALTER TABLE `document_lines` DROP FOREIGN KEY `document_lines_productId_fkey`;
ALTER TABLE `document_lines` DROP FOREIGN KEY `document_lines_unitId_fkey`;
ALTER TABLE `documents` DROP FOREIGN KEY `documents_created_by_fkey`;
ALTER TABLE `documents` DROP FOREIGN KEY `documents_customer_id_fkey`;
ALTER TABLE `documents` DROP FOREIGN KEY `documents_salesperson_id_fkey`;
ALTER TABLE `inventory` DROP FOREIGN KEY `inventory_warehouse_zone_id_fkey`;
ALTER TABLE `payment_records` DROP FOREIGN KEY `payment_records_created_by_fkey`;
ALTER TABLE `payment_records` DROP FOREIGN KEY `payment_records_document_id_fkey`;
ALTER TABLE `product` DROP FOREIGN KEY `product_categoryId_fkey`;
ALTER TABLE `product_brand` DROP FOREIGN KEY `product_brand_brandId_fkey`;
ALTER TABLE `product_brand` DROP FOREIGN KEY `product_brand_productId_fkey`;
ALTER TABLE `product_image` DROP FOREIGN KEY `product_image_specId_fkey`;
ALTER TABLE `purchase_inbound_lines` DROP FOREIGN KEY `purchase_inbound_lines_inbound_id_fkey`;
ALTER TABLE `purchase_price` DROP FOREIGN KEY `purchase_price_specId_fkey`;
ALTER TABLE `purchase_price` DROP FOREIGN KEY `purchase_price_supplierId_fkey`;
ALTER TABLE `purchase_price` DROP FOREIGN KEY `purchase_price_unitId_fkey`;
ALTER TABLE `purchase_spec_point` DROP FOREIGN KEY `purchase_spec_point_specId_fkey`;
ALTER TABLE `refund_lines` DROP FOREIGN KEY `refund_lines_created_by_fkey`;
ALTER TABLE `refund_lines` DROP FOREIGN KEY `refund_lines_line_id_fkey`;
ALTER TABLE `reimbursement_bill_lines` DROP FOREIGN KEY `reimbursement_bill_lines_bill_id_fkey`;
ALTER TABLE `reimbursement_bills` DROP FOREIGN KEY `reimbursement_bills_created_by_fkey`;
ALTER TABLE `reimbursement_bills` DROP FOREIGN KEY `reimbursement_bills_source_document_id_fkey`;
ALTER TABLE `sale_price` DROP FOREIGN KEY `sale_price_priceTypeId_fkey`;
ALTER TABLE `sale_price` DROP FOREIGN KEY `sale_price_specId_fkey`;
ALTER TABLE `sale_price` DROP FOREIGN KEY `sale_price_unitId_fkey`;
ALTER TABLE `sale_spec_point` DROP FOREIGN KEY `sale_spec_point_priceTypeId_fkey`;
ALTER TABLE `sale_spec_point` DROP FOREIGN KEY `sale_spec_point_specId_fkey`;
ALTER TABLE `spec` DROP FOREIGN KEY `spec_brandId_fkey`;
ALTER TABLE `spec` DROP FOREIGN KEY `spec_productId_fkey`;
ALTER TABLE `spec_unit` DROP FOREIGN KEY `spec_unit_specId_fkey`;
ALTER TABLE `spec_unit` DROP FOREIGN KEY `spec_unit_unit_fk`;
ALTER TABLE `supplier_address` DROP FOREIGN KEY `supplier_address_addressTypeId_fkey`;
ALTER TABLE `supplier_address` DROP FOREIGN KEY `supplier_address_supplierId_fkey`;
ALTER TABLE `supplier_business_brand` DROP FOREIGN KEY `supplier_business_brand_brandId_fkey`;
ALTER TABLE `supplier_business_brand` DROP FOREIGN KEY `supplier_business_brand_supplierId_fkey`;
ALTER TABLE `supplier_business_category` DROP FOREIGN KEY `supplier_business_category_categoryId_fkey`;
ALTER TABLE `supplier_business_category` DROP FOREIGN KEY `supplier_business_category_supplierId_fkey`;
ALTER TABLE `supplier_contact` DROP FOREIGN KEY `supplier_contact_supplierId_fkey`;
ALTER TABLE `user_roles` DROP FOREIGN KEY `user_roles_role_id_fkey`;
ALTER TABLE `user_roles` DROP FOREIGN KEY `user_roles_user_id_fkey`;
ALTER TABLE `warehouse_contact` DROP FOREIGN KEY `warehouse_contact_warehouseId_fkey`;
ALTER TABLE `warehouse_zone` DROP FOREIGN KEY `warehouse_zone_warehouseId_fkey`;
ALTER TABLE `access_requests` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `access_requests` MODIFY COLUMN `reviewedBy` BIGINT UNSIGNED NULL;
ALTER TABLE `address_type` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `allocation_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `allocation_lines` MODIFY COLUMN `line_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `allocation_lines` MODIFY COLUMN `source_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `allocation_lines` MODIFY COLUMN `excess_target_warehouse_id` BIGINT UNSIGNED NULL;
ALTER TABLE `allocation_lines` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `archived_costs` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `archived_costs` MODIFY COLUMN `original_document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_logistics` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `archived_logistics` MODIFY COLUMN `original_document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_order_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `archived_order_lines` MODIFY COLUMN `archived_order_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_orders` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `archived_orders` MODIFY COLUMN `original_document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_orders` MODIFY COLUMN `customer_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_orders` MODIFY COLUMN `salesperson_id` BIGINT UNSIGNED NULL;
ALTER TABLE `archived_refunds` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `archived_refunds` MODIFY COLUMN `original_document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_refunds` MODIFY COLUMN `line_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `archived_refunds` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `audit_logs` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `audit_logs` MODIFY COLUMN `user_id` BIGINT UNSIGNED NULL;
ALTER TABLE `audit_logs` MODIFY COLUMN `customer_id` BIGINT UNSIGNED NULL;
ALTER TABLE `audit_logs` MODIFY COLUMN `resource_id` BIGINT UNSIGNED NULL;
ALTER TABLE `authorization_codes` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `authorization_codes` MODIFY COLUMN `createdBy` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `backorders` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `backorders` MODIFY COLUMN `document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `backorders` MODIFY COLUMN `line_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `backorders` MODIFY COLUMN `warehouse_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `backorders` MODIFY COLUMN `brand_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `backorders` MODIFY COLUMN `unit_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `backorders` MODIFY COLUMN `fulfilled_by` BIGINT UNSIGNED NULL;
ALTER TABLE `backorders` MODIFY COLUMN `spec_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `brand` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `brand_unit_conversion` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `brand_unit_conversion` MODIFY COLUMN `unitId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `brand_unit_conversion` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `contact_method` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `cost_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `cost_lines` MODIFY COLUMN `line_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `cost_lines` MODIFY COLUMN `source_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `cost_lines` MODIFY COLUMN `inbound_line_id` BIGINT UNSIGNED NULL;
ALTER TABLE `cost_lines` MODIFY COLUMN `verified_by` BIGINT UNSIGNED NULL;
ALTER TABLE `customer_addresses` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_addresses` MODIFY COLUMN `customerId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `customer_contact` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_contact` MODIFY COLUMN `customerId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `customer_invoice` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_invoice` MODIFY COLUMN `customerId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `customer_sessions` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_sessions` MODIFY COLUMN `customerId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `customer_sessions` MODIFY COLUMN `authorizationCodeId` BIGINT UNSIGNED NULL;
ALTER TABLE `customer_type` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `customers` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `delivery_records` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `delivery_records` MODIFY COLUMN `document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `document_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `document_lines` MODIFY COLUMN `documentId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `document_lines` MODIFY COLUMN `brandId` BIGINT UNSIGNED NULL;
ALTER TABLE `document_lines` MODIFY COLUMN `unitId` BIGINT UNSIGNED NULL;
ALTER TABLE `document_lines` MODIFY COLUMN `productId` BIGINT UNSIGNED NULL;
ALTER TABLE `document_lines` MODIFY COLUMN `specId` BIGINT UNSIGNED NULL;
ALTER TABLE `documents` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `documents` MODIFY COLUMN `customer_id` BIGINT UNSIGNED NULL;
ALTER TABLE `documents` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `documents` MODIFY COLUMN `salesperson_id` BIGINT UNSIGNED NULL;
ALTER TABLE `field_change_logs` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `field_change_logs` MODIFY COLUMN `record_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `field_change_logs` MODIFY COLUMN `changed_by` BIGINT UNSIGNED NULL;
ALTER TABLE `inbound_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `inbound_lines` MODIFY COLUMN `task_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_lines` MODIFY COLUMN `line_id` BIGINT UNSIGNED NULL;
ALTER TABLE `inbound_lines` MODIFY COLUMN `brand_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_lines` MODIFY COLUMN `unit_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_lines` MODIFY COLUMN `spec_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_tasks` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `inbound_tasks` MODIFY COLUMN `document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_tasks` MODIFY COLUMN `supplier_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_tasks` MODIFY COLUMN `target_warehouse_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inbound_tasks` MODIFY COLUMN `confirmed_by` BIGINT UNSIGNED NULL;
ALTER TABLE `inventory` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `inventory` MODIFY COLUMN `warehouse_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory` MODIFY COLUMN `brand_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory` MODIFY COLUMN `unit_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory` MODIFY COLUMN `spec_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory` MODIFY COLUMN `warehouse_zone_id` BIGINT UNSIGNED NULL;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `warehouse_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `brand_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `unit_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `line_id` BIGINT UNSIGNED NULL;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `inventory_ledger` MODIFY COLUMN `spec_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `payment_records` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `payment_records` MODIFY COLUMN `document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `payment_records` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `price_type` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `product` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_brand` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_brand` MODIFY COLUMN `productId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `product_brand` MODIFY COLUMN `brandId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `product_image` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_image` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbound_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `purchase_inbound_lines` MODIFY COLUMN `inbound_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbound_lines` MODIFY COLUMN `spec_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbound_lines` MODIFY COLUMN `brand_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbound_lines` MODIFY COLUMN `unit_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbounds` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `purchase_inbounds` MODIFY COLUMN `supplier_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbounds` MODIFY COLUMN `warehouse_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_inbounds` MODIFY COLUMN `confirmed_by` BIGINT UNSIGNED NULL;
ALTER TABLE `purchase_price` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `purchase_price` MODIFY COLUMN `unitId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_price` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_price` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_spec_point` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `purchase_spec_point` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `purchase_spec_point` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `refund_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `refund_lines` MODIFY COLUMN `line_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `refund_lines` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `refund_lines` MODIFY COLUMN `restock_warehouse_id` BIGINT UNSIGNED NULL;
ALTER TABLE `reimbursement_bill_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `reimbursement_bill_lines` MODIFY COLUMN `bill_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `reimbursement_bills` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `reimbursement_bills` MODIFY COLUMN `source_document_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `reimbursement_bills` MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL;
ALTER TABLE `sale_point_rule` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `sale_point_rule` MODIFY COLUMN `priceTypeId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `sale_price` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `sale_price` MODIFY COLUMN `unitId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `sale_price` MODIFY COLUMN `priceTypeId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `sale_price` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `sale_spec_point` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `sale_spec_point` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `sale_spec_point` MODIFY COLUMN `priceTypeId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `spec` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `spec` MODIFY COLUMN `productId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `spec` MODIFY COLUMN `brandId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `spec_unit` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `spec_unit` MODIFY COLUMN `specId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `spec_unit` MODIFY COLUMN `unitId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_address` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_address` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier_address` MODIFY COLUMN `addressTypeId` BIGINT UNSIGNED NULL;
ALTER TABLE `supplier_business_brand` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_business_brand` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier_business_brand` MODIFY COLUMN `brandId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier_business_category` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_business_category` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier_contact` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_contact` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier_payable_lines` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_payable_lines` MODIFY COLUMN `supplier_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `supplier_payable_lines` MODIFY COLUMN `document_id` BIGINT UNSIGNED NULL;
ALTER TABLE `supplier_payable_lines` MODIFY COLUMN `line_id` BIGINT UNSIGNED NULL;
ALTER TABLE `supplier_point_rule` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_point_rule` MODIFY COLUMN `supplierId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `unit` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_roles` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_roles` MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `warehouse` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `warehouse_contact` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `warehouse_contact` MODIFY COLUMN `warehouseId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `warehouse_zone` MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `warehouse_zone` MODIFY COLUMN `warehouseId` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `access_requests` ADD CONSTRAINT `access_requests_reviewedBy_fkey` FOREIGN KEY (`reviewedBy`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `allocation_lines` ADD CONSTRAINT `allocation_lines_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `allocation_lines` ADD CONSTRAINT `allocation_lines_line_id_fkey` FOREIGN KEY (`line_id`) REFERENCES `document_lines` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `allocation_lines` ADD CONSTRAINT `allocation_lines_source_id_fkey` FOREIGN KEY (`source_id`) REFERENCES `supplier` (`id`) ON UPDATE CASCADE;
ALTER TABLE `archived_costs` ADD CONSTRAINT `archived_costs_original_document_id_fkey` FOREIGN KEY (`original_document_id`) REFERENCES `documents` (`id`) ON UPDATE CASCADE;
ALTER TABLE `archived_logistics` ADD CONSTRAINT `archived_logistics_original_document_id_fkey` FOREIGN KEY (`original_document_id`) REFERENCES `documents` (`id`) ON UPDATE CASCADE;
ALTER TABLE `archived_order_lines` ADD CONSTRAINT `archived_order_lines_archived_order_id_fkey` FOREIGN KEY (`archived_order_id`) REFERENCES `archived_orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `archived_orders` ADD CONSTRAINT `archived_orders_original_document_id_fkey` FOREIGN KEY (`original_document_id`) REFERENCES `documents` (`id`) ON UPDATE CASCADE;
ALTER TABLE `audit_logs` ADD CONSTRAINT `audit_logs_customer_id_fkey` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `audit_logs` ADD CONSTRAINT `audit_logs_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `authorization_codes` ADD CONSTRAINT `authorization_codes_createdBy_fkey` FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`) ON UPDATE CASCADE;
ALTER TABLE `brand_unit_conversion` ADD CONSTRAINT `brand_unit_conversion_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `brand_unit_conversion` ADD CONSTRAINT `brand_unit_conversion_unitId_fkey` FOREIGN KEY (`unitId`) REFERENCES `unit` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cost_lines` ADD CONSTRAINT `cost_lines_line_id_fkey` FOREIGN KEY (`line_id`) REFERENCES `document_lines` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cost_lines` ADD CONSTRAINT `cost_lines_source_id_fkey` FOREIGN KEY (`source_id`) REFERENCES `supplier` (`id`) ON UPDATE CASCADE;
ALTER TABLE `cost_lines` ADD CONSTRAINT `cost_lines_verified_by_fkey` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `customer_addresses` ADD CONSTRAINT `customer_addresses_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `customer_contact` ADD CONSTRAINT `customer_contact_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `customer_invoice` ADD CONSTRAINT `customer_invoice_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `customer_sessions` ADD CONSTRAINT `customer_sessions_authorizationCodeId_fkey` FOREIGN KEY (`authorizationCodeId`) REFERENCES `authorization_codes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `customer_sessions` ADD CONSTRAINT `customer_sessions_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `delivery_records` ADD CONSTRAINT `delivery_records_document_id_fkey` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `document_lines` ADD CONSTRAINT `document_lines_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `brand` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `document_lines` ADD CONSTRAINT `document_lines_documentId_fkey` FOREIGN KEY (`documentId`) REFERENCES `documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `document_lines` ADD CONSTRAINT `document_lines_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `product` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `document_lines` ADD CONSTRAINT `document_lines_unitId_fkey` FOREIGN KEY (`unitId`) REFERENCES `unit` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `documents` ADD CONSTRAINT `documents_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `documents` ADD CONSTRAINT `documents_customer_id_fkey` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `documents` ADD CONSTRAINT `documents_salesperson_id_fkey` FOREIGN KEY (`salesperson_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `inventory` ADD CONSTRAINT `inventory_warehouse_zone_id_fkey` FOREIGN KEY (`warehouse_zone_id`) REFERENCES `warehouse_zone` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `payment_records` ADD CONSTRAINT `payment_records_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `payment_records` ADD CONSTRAINT `payment_records_document_id_fkey` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `product` ADD CONSTRAINT `product_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `category` (`id`) ON UPDATE CASCADE;
ALTER TABLE `product_brand` ADD CONSTRAINT `product_brand_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `brand` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `product_brand` ADD CONSTRAINT `product_brand_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `product` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `product_image` ADD CONSTRAINT `product_image_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `purchase_inbound_lines` ADD CONSTRAINT `purchase_inbound_lines_inbound_id_fkey` FOREIGN KEY (`inbound_id`) REFERENCES `purchase_inbounds` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `purchase_price` ADD CONSTRAINT `purchase_price_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `purchase_price` ADD CONSTRAINT `purchase_price_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `supplier` (`id`) ON UPDATE CASCADE;
ALTER TABLE `purchase_price` ADD CONSTRAINT `purchase_price_unitId_fkey` FOREIGN KEY (`unitId`) REFERENCES `unit` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `purchase_spec_point` ADD CONSTRAINT `purchase_spec_point_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `refund_lines` ADD CONSTRAINT `refund_lines_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `refund_lines` ADD CONSTRAINT `refund_lines_line_id_fkey` FOREIGN KEY (`line_id`) REFERENCES `document_lines` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `reimbursement_bill_lines` ADD CONSTRAINT `reimbursement_bill_lines_bill_id_fkey` FOREIGN KEY (`bill_id`) REFERENCES `reimbursement_bills` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `reimbursement_bills` ADD CONSTRAINT `reimbursement_bills_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `reimbursement_bills` ADD CONSTRAINT `reimbursement_bills_source_document_id_fkey` FOREIGN KEY (`source_document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `sale_price` ADD CONSTRAINT `sale_price_priceTypeId_fkey` FOREIGN KEY (`priceTypeId`) REFERENCES `price_type` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `sale_price` ADD CONSTRAINT `sale_price_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `sale_price` ADD CONSTRAINT `sale_price_unitId_fkey` FOREIGN KEY (`unitId`) REFERENCES `unit` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `sale_spec_point` ADD CONSTRAINT `sale_spec_point_priceTypeId_fkey` FOREIGN KEY (`priceTypeId`) REFERENCES `price_type` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `sale_spec_point` ADD CONSTRAINT `sale_spec_point_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `spec` ADD CONSTRAINT `spec_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `brand` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `spec` ADD CONSTRAINT `spec_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `product` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `spec_unit` ADD CONSTRAINT `spec_unit_specId_fkey` FOREIGN KEY (`specId`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `spec_unit` ADD CONSTRAINT `spec_unit_unit_fk` FOREIGN KEY (`unitId`) REFERENCES `unit` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `supplier_address` ADD CONSTRAINT `supplier_address_addressTypeId_fkey` FOREIGN KEY (`addressTypeId`) REFERENCES `address_type` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `supplier_address` ADD CONSTRAINT `supplier_address_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `supplier` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `supplier_business_brand` ADD CONSTRAINT `supplier_business_brand_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `brand` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `supplier_business_brand` ADD CONSTRAINT `supplier_business_brand_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `supplier` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `supplier_business_category` ADD CONSTRAINT `supplier_business_category_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `supplier_business_category` ADD CONSTRAINT `supplier_business_category_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `supplier` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `supplier_contact` ADD CONSTRAINT `supplier_contact_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `supplier` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `user_roles` ADD CONSTRAINT `user_roles_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `user_roles` ADD CONSTRAINT `user_roles_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `warehouse_contact` ADD CONSTRAINT `warehouse_contact_warehouseId_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `warehouse` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `warehouse_zone` ADD CONSTRAINT `warehouse_zone_warehouseId_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `warehouse` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
